services:
  postgres:
    image: postgres:latest
    container_name: librarycontainer
    restart: always
    environment:
      POSTGRES_DB: librarydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
